apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  template:
    metadata:
      labels:
        name: mongo
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: mongo
      template:
        metadata:
          labels:
            name: mongo
        spec:
          containers:
          - image: quay.io/mavazque/mongodb:autors
            imagePullPolicy: Always
            name: mongo
            env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mongodb-secret
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mongodb-secret
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-admin-password
                  name: mongodb-secret
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: mongodb-secret
            - name: MONGODB_KEYFILE_VALUE
              valueFrom:
                secretKeyRef:
                  key: keyfile-value
                  name: mongodb-secret
            - name: MONGODB_REPLICA_NAME
              value: "rs0"
            - name: PRIMARY_NODE
              value: "mongo-east1.apps.east-1.example1.com:443"
            - name: REPLICA_MEMBERS
              value: "mongo-east1.apps.east-1.example1.com:443,mongo-east2.apps.east-2.example1.com:443,mongo-west2.apps.west-2.example1.com:443"
            ports:
            - name: mongo
              containerPort: 27017
            volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
            - mountPath: /opt/mongo-ssl/
              name: mongodb-ssl
            - mountPath: /var/tmp/podinfo
              name: pod-info
          volumes:
          - name: mongodb-data
            persistentVolumeClaim:
              claimName: mongo
          - name: mongodb-ssl
            secret:
              secretName: mongodb-ssl
          - name: pod-info
            downwardAPI:
              items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              type: array
  placement:
    clusterNames:
    - east1
    - east2
    - west2
