resources:
- pacman-secret.yaml
- pacman-service.yaml
- pacman-route.yaml
- pacman-service-account.yaml
- pacman-cluster-role.yaml
- pacman-cluster-role-binding.yaml
- pacman-deployment.yaml
- pacman-namespace.yaml
